//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTaller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Movimiento
    {
        public int IdBitacoraMovimiento { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaHoraMovimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public string DetalleMovimiento { get; set; }
        public string IdRef { get; set; }
    }
}
