//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTaller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public int IdCotizacion { get; set; }
        public int CodCotizacion { get; set; }
        public string NPlaca { get; set; }
        public string Cedula { get; set; }
        public string NombreClien { get; set; }
        public string TelefClien { get; set; }
        public string Email { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NServicio { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public int Total { get; set; }
        public int Vigencia { get; set; }
        public string NEmpleado { get; set; }
    }
}
