//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTaller.Models
{
    using System;
    
    public enum Estilo : int
    {
        SEDAN = 1,
        HATCHBACK = 2,
        PICKUP4X2 = 3,
        PICKUP4x4 = 4,
        TODO_TERRENO_4x2 = 5,
        TODO_TERRENO_4x4 = 6,
        MICROBUS_MINIVAN = 7
    }
}
