//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasicologiaBelen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int IdHistorico { get; set; }
        public int IdPlaca { get; set; }
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public int IdServicio { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaReparacion { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int IdEmpleado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Placa Placa { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
